project:
  type: website
  output-dir: docs

format:
  html:
    author: Vincent D.
    theme: yeti
    css: styles.css
    execute: True
    freeze: False
    code-fold: true
    code-line-numbers: true
    code-tools:
      source: repo
    highlight-style: dracula

website:
  title: "Portfolio Geek"
  site-url: "portfolio-geek.com"
  repo-url: "https://github.com/vdenoise/portfolio-geek/"
  description: "Finance, Research and the Tech required to Fuel them"
  repo-branch: "master"
  navbar:
    right:
      - text: Blog
        href: all_posts.qmd
      - text: About
        href: about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/vdenoiseux/
      - icon: github
        href: https://github.com/vdenoise 
      - icon: twitter
        href: https://twitter.com
      - text: Ressources
        menu: 
          - text: Portfolio Construction
            href: risk_and_return.qmd
          - text: Real Python
            href: https://realpython.com/
