project:
  type: website
  output-dir: docs

format:
  html:
    author: Vincent D.
    theme: yeti
    css: styles.css
    execute: True
    freeze: False
    code-fold: true
    link-external-newwindow: true
    code-line-numbers: true
    code-tools:
      source: repo
    highlight-style: dracula

website:
  title: "Portfolio Geek"
  site-url: "https://portfolio-geek.com"
  site-path: "/"
  google-analytics: 
    tracking-id: "G-CJ2CMCX5LZ"
    anonymize-ip: true
  cookie-consent:
    type: express
    style: headline
    palette: dark
  repo-url: "https://github.com/vdenoise/portfolio-geek/"
  description: "Finance, Research and the Tech required to Fuel them"
  repo-branch: "master"
  navbar:
    right:
      - text: Getting Started
        href: tutorials_en.qmd
      - text: All Articles
        href: all_posts.qmd
      - text: About
        href: about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/vdenoiseux/
      - icon: github
        href: https://github.com/vdenoise 
      - icon: twitter
        href: https://twitter.com
      - text: Ressources
        menu: 
          - text: Measuring Risk and Return
            href: risk_and_return.qmd
          - text: Portfolio Construction
            href: portfolio_construction.qmd
          - text: Tutorials (en)
            href: tutorials_en.qmd

