project:
  type: website
  output-dir: site
  resources:
  - "pictures/*"

format:
  html:
    author: Vincent D.
    theme: yeti
    css: styles.css
    execute: True
    freeze: False
    code-fold: true
    link-external-newwindow: true
    code-line-numbers: true
    highlight-style: dracula
    code-tools:
      source: true
      toggle: false
      caption: none

website:
  title: "Portfolio Geek"
  open-graph: true
  site-url: "https://portfolio-geek.com"
  site-path: "/"

  google-analytics: 
    tracking-id: "G-CJ2CMCX5LZ"
    anonymize-ip: true
  cookie-consent:
    type: express
    style: headline
    palette: light
  repo-url: "https://github.com/vdenoise/portfolio-geek/"

  description: "Finance, Research and the Tech required to Fuel them"
  repo-branch: "master"
  navbar:
    right:
      - text: Daily Findings
        href: daily-curation.qmd
      - text: Getting Started
        href: tutorials_en.qmd
      - text: About
        href: about.qmd
      - icon: rss
        href: index.xml
      - icon: linkedin
        href: https://www.linkedin.com/in/vdenoiseux/
      - icon: github
        href: https://github.com/vdenoise 
      - icon: twitter
        href: https://twitter.com
  page-footer:
    left: |
      Proudly propelled by [Quarto](https://quarto.org/)
    center:
      - text: "About | Copyright | Disclaimer"
        href: about.qmd